spring:
  application:
    name: ms-transaction
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8090

#eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka